### ISSUE TITLE
Progress tracking

### ISSUE THREAD

**Issue by cassc** [sbip-sg/tevm#2]
This list will be updated while fixing the [tests](https://github.com/sbip-sg/tevm/tree/develop/tests) and benchmarks

- [x] deterministic_deploy: REVM has removed [CREATE2 support](https://github.com/bluealloy/revm/issues/1182) from the transaction. The recommended alternative solution is to "change address after execution". This will introduce a breaking change in the Python API.
> (from REVM) The reason why it is removed is that CREATE2 is a opcode and can't be called outside of Revm. I can't think of easy way to do it.  You can deploy it with CREATE and just change addresses after execution.
- [x] migrate bug data from tinyevm
- [x] figure out how to use the new inspector pattern
- [x] Fix failed Rust tests:
  - [x] tevm::revm_test test_bug_data_in_deploy
  - [x] tevm::revm_test test_blockhash
  - [x] tevm::revm_test test_deploy_with_args_and_value
  - [x] tevm::revm_test test_deterministic_deploy
  - [x] tevm::revm_test test_contract_method_revert
  - [x] tevm::revm_test test_div_zero
  - [x] tevm::revm_test test_deterministic_deploy_overwrite
  - [x] tevm::revm_test test_call_forked_contract_from_local_contract
  - [x] tevm::revm_test test_contract_deploy_transfer_query
  - [x] tevm::revm_test test_get_set_balance
  - [x] tevm::revm_test test_fork
  - [x] tevm::revm_test test_call_trace
  - [x] tevm::revm_test test_distance_signed
  - [x] tevm::revm_test test_integer_truncation
  - [x] tevm::revm_test test_exp_overflow
  - [x] tevm::revm_test test_events
  - [x] tevm::revm_test test_deadloop
  - [x] tevm::revm_test test_reset_storage
  - [x] tevm::revm_test test_overflow
  - [x] tevm::revm_test test_revert_or_invalid
  - [x] tevm::revm_test test_heuristics
  - [x] tevm::revm_test test_seen_pcs
  - [x] tevm::revm_test test_heuristics_signed_int
  - [x] tevm::revm_test test_set_get_code
  - [x] tevm::revm_test test_set_get_storage
  - [x] tevm::revm_test test_peephole_optimized_if_equal
  - [x] tevm::revm_test test_mod_zero
  - [x] tevm::revm_test test_timestamp_and_block_number
  - [x] tevm::revm_test test_runtime_configuration
  - [x] tevm::revm_test test_seen_addresses
  - [x] tevm::revm_test test_selfdestruct_and_create
  - [x] tevm::revm_test test_sha3_mapping
  - [x] tevm::revm_test test_tx_origin
  - [x] tevm::revm_test test_tod
  - [x] tevm::revm_test test_tx_origin_v2
  - [x] tevm::revm_test test_gas_usage
  - [x] tevm::revm_test test_library_method_with_large_string
  - [x] tevm::revm_test test_sturdy_hack

- **Fix Failed Tests in Redis Version**

  - [x] tevm::revm_test test_bug_data_in_deploy
  - [x] tevm::revm_test test_blockhash
  - [x] tevm::revm_test test_deploy_with_args_and_value
  - [x] tevm::revm_test test_deterministic_deploy
  - [x] tevm::revm_test test_contract_method_revert
  - [x] tevm::revm_test test_div_zero
  - [x] tevm::revm_test test_deterministic_deploy_overwrite
  - [x] tevm::revm_test test_call_forked_contract_from_local_contract
  - [x] tevm::revm_test test_contract_deploy_transfer_query
  - [x] tevm::revm_test test_get_set_balance
  - [x] tevm::revm_test test_fork
  - [x] tevm::revm_test test_call_trace
  - [x] tevm::revm_test test_distance_signed
  - [x] tevm::revm_test test_integer_truncation
  - [x] tevm::revm_test test_exp_overflow
  - [x] tevm::revm_test test_events
  - [x] tevm::revm_test test_deadloop
  - [x] tevm::revm_test test_reset_storage
  - [x] tevm::revm_test test_overflow
  - [x] tevm::revm_test test_revert_or_invalid
  - [x] tevm::revm_test test_heuristics
  - [x] tevm::revm_test test_seen_pcs
  - [x] tevm::revm_test test_heuristics_signed_int
  - [x] tevm::revm_test test_set_get_code
  - [x] tevm::revm_test test_set_get_storage
  - [x] tevm::revm_test test_peephole_optimized_if_equal
  - [x] tevm::revm_test test_mod_zero
  - [x] tevm::revm_test test_timestamp_and_block_number
  - [x] tevm::revm_test test_runtime_configuration
  - [x] tevm::revm_test test_seen_addresses
  - [x] tevm::revm_test test_selfdestruct_and_create
  - [x] tevm::revm_test test_sha3_mapping
  - [x] tevm::revm_test test_tx_origin
  - [x] tevm::revm_test test_tod
  - [x] tevm::revm_test test_tx_origin_v2
  - [x] tevm::revm_test test_gas_usage
  - [x] tevm::revm_test test_library_method_with_large_string
  - [x] tevm::revm_test test_sturdy_hack

- **Fix Python tests:**
  - [x] tests/test_account_snapshot.py::test_account_snapshot - RuntimeError: Invalid string length
  - [x] tests/test_account_snapshot.py::test_redeploy - TypeError: argument 'deploy_to_address': 'NoneType' object cannot be converted to 'PyString'
  - [x] tests/test_global_snapshot.py::test_global_snapshot[x_fns0-False-fastseq take and restore snapshot] - RuntimeError: Invalid string length
  - [x] tests/test_global_snapshot.py::test_global_snapshot[x_fns1-False-slowseq take and restore snapshot] - RuntimeError: Invalid string length
  - [x] tests/test_global_snapshot.py::test_global_snapshot[x_fns2-True-fastseq no snapshot] - RuntimeError: Invalid string length
  - [x] tests/test_global_snapshot.py::test_global_snapshot[x_fns3-True-slowseq no snapshot] - RuntimeError: Invalid string length
  - [x] tests/test_global_snapshot.py::test_compare_memory - RuntimeError: Invalid string length
  - [x] tests/test_tinyevm.py::TestTinyEVM::test_deployment - TypeError: argument 'deploy_to_address': 'NoneType' object cannot be converted to 'PyString'
  - [x] tests/test_tinyevm.py::TestTinyEVM::test_get_change_tx_gas_limit - AttributeError: 'builtins.TinyEVM' object has no attribute 'tx_gas_limit'
  - [x] tests/test_tinyevm.py::TestTinyEVM::test_get_set_env_field - assert '"0x0"' == '0x0000000000...0000000000000'
  - [x] tests/test_tinyevm.py::TestTinyEVM::test_instrument_config - AttributeError: 'builtins.REVMConfig' object has no attribute 'enabled'

- [x] benchmark comparison with TinyEVM.
  - Python benchmarks from TinyEVM (from `pytest`)
![tinyevm-2024-07-17_12-48](https://github.com/user-attachments/assets/b7f29715-f356-42e8-91b4-21a24dfc4001)
  - Python benchmarks from TEVM (from `pytest`)
![tevm-2024-07-17_12-06](https://github.com/user-attachments/assets/10045253-a2ff-4fa4-a0c4-4dda5c150e4c)

  - Rust benchmarks (from `cargo bench`), left side is from TEVM, right side is from TinyEVM. Test in which TEVM performs worse than TinyEVM are marked with red rectangle: [cargo-bench-comparison.pdf](https://github.com/user-attachments/files/16263111/cargo-bench-comparison.pdf)
- Benchmark conclusion: while in most tests TEVM out performs TinyEVM, it performs worse at some tests:
  1. Python `test_redeploy` and significantly at `test_account_snapshot` ([todo](https://github.com/sbip-sg/tevm/issues/5))
  2. Rust `bench_call_tracing_with_different_executor` and `bench_contract_deploy_on_different_executors`, this suggests TEVM is more expensive to create than TinyEVM
